//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AambyPlanning
{

    public partial class CreateUser
    {
        /// <summary>
        /// lblStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;

        /// <summary>
        /// dform control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dform;

        /// <summary>
        /// txtUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUserName;

        /// <summary>
        /// rfvUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUserName;

        /// <summary>
        /// txtEmpId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmpId;

        /// <summary>
        /// rfvEmpId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmpId;

        /// <summary>
        /// txtEmpName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmpName;

        /// <summary>
        /// rfvEmpName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmpName;

        /// <summary>
        /// ddlProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlProfile;

        /// <summary>
        /// rfvProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvProfile;

        /// <summary>
        /// txtMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMobile;

        /// <summary>
        /// rfvMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMobile;

        /// <summary>
        /// revMobile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revMobile;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// rfvEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// revEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;
    }
}
